### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Vrekt** [AKZOMBIE74/QuizletAPI#1]
I've been looking for something like this for awhile. I was just wondering where I can get the setID and if its possible if you could provide an example usage. Thank you

**Comment by amin-codes** [comment]
The set id is within the URL. Also, check the readme file for an example.

For example in the url: https://quizlet.com/234104177/biology-vocabulary-4-flash-cards/
Set ID = 234104177

Note: I am not the creator of the quizlet set used in the example.

**Comment by Vrekt** [comment]
Ah yeah I was able to get it working couple hours after I posted this issue. Do you know if Quizlet allows searching for something and grabbing setID of the search results?

**Comment by amin-codes** [comment]
You could try to see how Quizlet makes it’s searches, then use that same method to search for sets.

**Comment by Vrekt** [comment]
Gotcha, I'll look into it more. Thanks for the help and the API.

**Comment by amin-codes** [comment]
Also, I found this: https://quizlet.com/api/2.0/docs/searching-sets

**Comment by Northernside** [comment]
Uhm - how can I get a client ID?

**Comment by amin-codes** [comment]
The Quizlet API is no longer supported by Quizlet themselves. You can see this answer here: https://stackoverflow.com/questions/60425101/quizlet-api-not-available 

Sorry for the inconvenience.

**Comment by Northernside** [comment]
Oh man.. Thanks anyway!
